resources:
  pipelines:
    - pipeline: P2
      source: jainamanjain.Repo1

stages:
 - stage: Download_A1_1_artifact
   jobs:
     - job: J4
       pool: 
        name: default
       steps:
         - download: P2
           artifact: A1.1