resources:
  pipelines:
    - pipeline: P1
      source: jainamanjain.Repo1

stages:
 - stage: Download_A1_1_artifact
   jobs:
     - job: J4
       pool: 
        name: default
       steps:
         - download: P1
           artifact: A1.1
         - powershell: |
            ls $(Pipeline.Workspace)/